
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.31.121:3307/gulimall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.121:8848
  application:
    name: gulimail-ware
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 11000